43 label a sentence
buerokratt/Data-Anonymizer pull request #81
Opened 2022-11-21 10:53 UTC by alimuhammadahmer

2022-11-29 11:33 UTC, turnerrainer requested changes

2022-11-29 11:33 UTC, turnerrainer commented on README.md
> +```
Please add a sample curl request.

2022-11-29 11:33 UTC, turnerrainer commented on README.md
> +```
Please add a sample curl request.

2022-11-29 15:13 UTC, alimuhammadahmer commented on README.md
> +```
Done

2022-12-01 02:53 UTC, turnerrainer requested changes
No newline at end of file, otherwise OK

2022-12-01 02:53 UTC, turnerrainer commented on DSL.Resql/upsert_corpora_task.sql
> +insert into Corpora_Tasks (id, raw_text, corpora_id, is_private, preannotated_text, annotated_text, sentences_annotations) select :id, raw_text, corpora_id, is_private, preannotated_text, :annotated_
No newline at end of file

2022-12-01 02:53 UTC, turnerrainer commented on DSL.Ruuter/POST/annotate.yml
> +  return: ${request_response.response.body}
No newline at end of file

2023-01-04 12:34 UTC, turnerrainer approved these changes

2023-01-05 14:31 UTC, merged