ISSUE-69: Upload private corpus to the database
buerokratt/Data-Anonymizer pull request #82
Opened 2022-11-21 11:02 UTC by alimuhammadahmer

This is a pull request for uploading a private corpus (which is a list of sentences) to database.

2022-11-29 11:33 UTC, turnerrainer requested changes

2022-11-29 11:33 UTC, turnerrainer commented on README.md
> +```
Please add a sample curl request.

2022-11-29 11:33 UTC, turnerrainer commented on README.md
> +```
Please add a sample curl request.

2022-11-29 15:13 UTC, alimuhammadahmer commented on README.md
> +```
Done

2022-11-29 15:13 UTC, alimuhammadahmer commented on README.md
> +```
Done

2022-12-01 02:52 UTC, turnerrainer requested changes
No newline at end of file, otherwise OK

2022-12-01 02:52 UTC, turnerrainer commented on DSL.Resql/insert_corpora_task.sql
> +insert into Corpora_Tasks (raw_text, corpora_id, is_private, created_at) VALUES (:raw_text, :corpora_id, :is_private, :created_at::timestamp) RETURNING id;
No newline at end of file

2022-12-06 09:51 UTC, alimuhammadahmer commented on DSL.Resql/insert_corpora_task.sql
> +insert into Corpora_Tasks (raw_text, corpora_id, is_private, created_at) VALUES (:raw_text, :corpora_id, :is_private, :created_at::timestamp) RETURNING id;
Done

2023-01-04 12:33 UTC, turnerrainer approved these changes

2023-01-05 14:30 UTC, merged