ISSUE-63: Delete added Regex pattern from database
buerokratt/Data-Anonymizer pull request #85
Opened 2022-11-22 10:22 UTC by alimuhammadahmer

This is a pull request which contains Ruuter and Resql endpoints to delete a regex record.

2022-11-29 11:14 UTC, turnerrainer requested changes

2022-11-29 11:14 UTC, turnerrainer commented on README.md
> +```
Please add a sample curl request.

2022-11-29 11:14 UTC, turnerrainer commented on README.md
> +```
Please add a sample curl request.

2022-11-29 11:14 UTC, turnerrainer commented on README.md
>  ```
Please add a sample curl request.

2022-11-29 15:09 UTC, alimuhammadahmer commented on README.md
> +```
Done

2022-11-29 15:09 UTC, alimuhammadahmer commented on README.md
>  ```
Done

2022-12-01 02:48 UTC, turnerrainer requested changes
No newline at end of file, otherwise OK

2022-12-01 02:48 UTC, turnerrainer commented on DSL.Resql/delete_regex.sql
> +insert into Regex_Entity (id, regex, entity, active) select id, regex, entity, False from Regex_Entity where id = :id ORDER BY created_at DESC limit 1;
No newline at end of file

2022-12-06 09:49 UTC, alimuhammadahmer commented on DSL.Resql/delete_regex.sql
> +insert into Regex_Entity (id, regex, entity, active) select id, regex, entity, False from Regex_Entity where id = :id ORDER BY created_at DESC limit 1;
Done

2022-12-15 06:01 UTC, turnerrainer approved these changes

2023-01-05 14:26 UTC, merged