ISSUE-89: Add new entity
buerokratt/Data-Anonymizer pull request #90
Opened 2022-11-23 10:02 UTC by alimuhammadahmer

This is a Pull Request containing Ruuter & Resql endpoints for adding a new entity.

2022-11-29 11:09 UTC, turnerrainer requested changes

2022-11-29 11:09 UTC, turnerrainer commented on README.md
> +```
Please add a sample curl request.

2022-11-29 11:09 UTC, turnerrainer commented on README.md
> +```
Please add a sample curl request.

2022-11-29 15:01 UTC, alimuhammadahmer commented on README.md
> +```
Done

2022-12-01 02:39 UTC, turnerrainer approved these changes

2022-12-01 02:39 UTC, merged