ISSUE-75: Describe Data Model for Application
buerokratt/Data-Anonymizer pull request #92
Opened 2022-11-23 12:51 UTC by alimuhammadahmer

This pull-request contains a Resql File for creating db schema.

2022-11-29 10:59 UTC, turnerrainer approved these changes

2022-11-29 11:10 UTC, turnerrainer requested changes

2022-11-29 11:10 UTC, turnerrainer commented on README.md
> +```
Please add a sample curl request.

2022-11-29 15:01 UTC, alimuhammadahmer commented on README.md
> +```
Done

2022-12-01 02:23 UTC, turnerrainer approved these changes

2023-01-05 11:12 UTC, merged